import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { toast } from 'react-toastify';

import api from '~/services/api';

import {
  updateProvaRequest,
  // updateEmProvaRequest,
  updateFimProvaRequest,
} from '~/store/modules/usuario/actions';

import icoConcluido from '~/assets/ico-concluido.jpg';

import {
  Container,
  Prod,
  ModUl,
  ModUl2,
  Titulo,
  Titulo2,
  Titulo3,
  Default,
  Danger,
  Ladodireito,
  Box1,
  Voltar,
  Teste,
  Numeros,
} from './styles';

export default function Grafico(props) {
  const [perfil, setPerfil] = useState();
  const [prova, setProva] = useState();
  const [provafinalizada, setProvafinalizada] = useState();
  const [porcentagem, setPorcentagem] = useState(0);
  const [testes, setTestes] = useState([]);

  const id = parseInt(props.match.params.id);

  const dispatch = useDispatch();

  // const dadosProva = useSelector((state) => state.usuario.prova);

  const perf = useSelector((state) => state.usuario);

  async function finalizarProva() {
    try {
      await api.delete(`provasaluno/${prova.id}`);

      const response = await api.get(`provasfinalizadas`);

      setProva(null);
      dispatch(updateFimProvaRequest());
      setProvafinalizada(response.data);

      toast.success('Prova finalizada com sucesso!');
    } catch (error) {
      toast.error('Erro ao finalizar a prova. Tente novamente!');
    }
  }

  async function loadProvas() {
    const response = await api.get(`provas`);

    console.log('Prova: ', response.data);

    setProva(response.data);
    dispatch(updateProvaRequest(response.data));

    const prova_id = response.data ? response.data.id : null;
  }

  async function loadTestes() {
    const response = await api.put(`testealuno/${id}`);

    console.log('Testes: ', response.data);

    setTestes(response.data);
  }

  useEffect(() => {
    async function loadPerfil() {
      setPerfil(perf.perfil);
    }

    loadPerfil();
  }, []);

  useEffect(() => {
    loadProvas();
    loadTestes();
  }, []);

  useEffect(() => {
    async function loadProvasFinalizadas() {
      const response2 = await api.get(`provasfinalizadas`);

      setProvafinalizada(response2.data);
    }

    loadProvasFinalizadas();
  }, []);

  return (
    <Container>
      <Voltar>
        <ul>
          <li>
            <Link to="/dashboard">
              <small>Home</small>
            </Link>
          </li>
          <li>|</li>
          <li>
            <small>Avaliando seu Desempenho</small>
          </li>
        </ul>

        <a href="javascript:history.back()">
          <small>&laquo; Voltar</small>
        </a>
      </Voltar>
      <Prod>
        <div>
          <Titulo>AVALIANDO O SEU DESEMPENHO</Titulo>
          <Titulo2>
            Gráfico demonstrativo em relação aos resultados dos 3 módulos
          </Titulo2>

          {testes.length ? (
            <Box1>
              <strong>Testes</strong>
              <strong>PCMs</strong>
              <small>Meta = 640 PCMs</small>
              <div>
                <Numeros>
                  <p>900</p>
                </Numeros>
                <Numeros>
                  <p>800</p>
                </Numeros>
                <Numeros>
                  <p>700</p>
                </Numeros>
                <Numeros>
                  <p>600</p>
                </Numeros>
                <Numeros>
                  <p>500</p>
                </Numeros>
                <Numeros>
                  <p>400</p>
                </Numeros>
                <Numeros>
                  <p>300</p>
                </Numeros>
                <Numeros>
                  <p>200</p>
                </Numeros>
                <Numeros>
                  <p>100</p>
                </Numeros>
                <Numeros>
                  <p>0</p>
                </Numeros>
                <Numeros> </Numeros>
              </div>
              {testes.map((t) => (
                <Teste key={t.id} height={t.pcm / 2} bg="blue">
                  <span>
                    <p>{t.pcm}</p>
                  </span>
                  {t.numero === 0 ? (
                    <span>
                      <p>Inicial</p>
                    </span>
                  ) : (
                    <span>
                      <p>{t.numero}</p>
                    </span>
                  )}
                </Teste>
              ))}
              {testes.length < 21 && (
                <>
                  {testes.length === 1 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 2 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 3 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 4 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 5 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 6 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 7 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 8 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 9 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 10 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 11 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 12 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 13 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 14 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 15 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 16 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 17 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 18 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 19 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                  {testes.length === 20 && (
                    <>
                      <Teste>
                        <span></span>
                        <span></span>
                      </Teste>
                    </>
                  )}
                </>
              )}
            </Box1>
          ) : (
            <Box1>
              <h2>Você ainda não fez testes.</h2>
            </Box1>
          )}
        </div>
      </Prod>
    </Container>
  );
}
